INFO - Log file for this run: /home/ilena7440/LSQ/out/MobileNetv2_cifar10_a8w8_5_20221102-131734/MobileNetv2_cifar10_a8w8_5_20221102-131734.log
INFO - TensorBoard data directory: /home/ilena7440/LSQ/out/MobileNetv2_cifar10_a8w8_5_20221102-131734/tb_runs
INFO - Dataset `cifar10` size:
          Training Set = 50000 (391)
        Validation Set = 10000 (79)
              Test Set = 10000 (79)
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 67, in main
    model = create_model(args)
  File "/home/ilena7440/LSQ/model/model.py", line 37, in create_model
    model = mobilenetv2_cifar10(pretrained = args.pre_trained)
  File "/home/ilena7440/LSQ/model/mobilenet_cifar10.py", line 178, in mobilenetv2_cifar10
    return _mobilenetv2('mobilenetv2', 1.0, pretrained, progress, num_classes = 10)
  File "/home/ilena7440/LSQ/model/mobilenet_cifar10.py", line 173, in _mobilenetv2
    state_dict = torch.load(model_path[arch], progress = progress)
  File "/home/ilena7440/qilbertenv/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ilena7440/qilbertenv/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ilena7440/qilbertenv/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './mobilenetv2/cifar10_pretrained.pth'
Files already downloaded and verified
Files already downloaded and verified
hello
********************pre-trained*****************